### ISSUE TITLE
Build output sometimes not shown in jenkins console output

### ISSUE THREAD

**Issue by tiwillia** [openshift/jenkins-plugin#125]
When triggering a build while using the `showBuildLogs: true` option, the build logs are sometimes not included in the jenkins console output.

This seems to occur when there is a delay in the build pod being scheduled, when the build pod sits in `New `state for some time. The jenkins plugin only checks for the pod once when the build is triggered, but won't check again until the build is completed.

This issue was experienced running v1.0.39 of the jenkins plugin on jenkins-1.651.2, using rhel7 images.

**Comment by gabemontero** [comment]
@tiwillia previously got me a repro with trace; believe I have a fix in the works

**Comment by gabemontero** [comment]
Commit https://github.com/openshift/jenkins-plugin/commit/816adf3763f948f98c1b4d8835b66e64a0cb75e1 has the fix

A pre-release version of the plugin with this fix is located at https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/34/s3/download/openshift-pipeline.hpi.  Install it in your jenkins server at your discretion.  Also, @tiwillia had the good idea of turning off concurrent builds for this jenkins job if they want to avoid or at least reduce the frequency of this issue in the interim, and not install this pre-release version of the plugin.

The openshift-pipeline release will be v1.0.41.

Our jenkins rhel images are on hold for the time being as we await some upstream jenkinsci plugins to get updated.  If I can remember I'll update this issue when the rhel7 image ultimately gets generated on brew-pulp; otherwise, just check in with me when needed about the status of that.

Closing this out.  Thanks.
