### ISSUE TITLE
Environment Variables don't respect Parameterised Builds

### ISSUE THREAD

**Issue by benemon** [openshift/jenkins-plugin#129]
*STEPS TO REPLICATE*

- Create Parameterised Build Job
- Add a String Parameter for 'JENKINS_FOO', with a value of 'FOO'
- Add an Trigger OpenShift Build Step
- Add an Environment Variable to the Trigger OpenShift Build Step
- NAME: BAR
- VALUE: ${JENKINS_FOO}
- Configure for some BC in your project
- Start Build
- Examine BC in OpenShift

*ACTUAL*:
- 'BAR=${JENKINS_FOO}' - value passed as a String Literal.

*EXPECTED*:
- 'BAR=FOO'

**Comment by benemon** [comment]
Further information for you.

**Versions**
Jenkins: 2.19.3
OpenShift Jenkins Plugin: 1.0.42
OpenShift Container Platform: 3.4.0.40


**Screenshots**




<img width="895" alt="trigger openshift build with env vars" src="https://cloud.githubusercontent.com/assets/4622553/22937374/4deb74f6-f2d0-11e6-81ff-ab4f4db8e05b.png">


<img width="1076" alt="start parameterised build" src="https://cloud.githubusercontent.com/assets/4622553/22936946/e69ec3a8-f2ce-11e6-896e-021c46c1c8ac.png">


<img width="1207" alt="result in openshift" src="https://cloud.githubusercontent.com/assets/4622553/22937387/5c6a7cc0-f2d0-11e6-82ca-b447693760d8.png">

**Comment by gabemontero** [comment]
@benemon  - Yep it looks like when bld env vars were added (relatively later than previous capabilities), we missed passing the values through our translation mechanism.

I should probably have a pre-release patch ready to try either later today or tomorrow.

Thanks for catching / reporting this.

**Comment by gabemontero** [comment]
https://github.com/openshift/jenkins-plugin/commit/d64f23ea6abb841fbeb5c9d527c3a85d3b075c03 has the fix for this.

I'll update the PR with a link and close when I have a pre release version of the plugin with this update.  That job is running as I type.

**Comment by gabemontero** [comment]
@benemon - hey, a built plugin file with the fix for this issue is located [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/35/s3/download/openshift-pipeline.hpi)

If you get a chance update the plugin installed in your jenkins image via the jenkins console with the above file to get the fix for this issue.  Of course reopen the issue if the change does not work for you.

I'll probably wait a few days before crafting a new official version and updating our jenkins centos image.  RPMs for the rhel image will probably happen as we get close to cutting 3.5.

**Comment by benemon** [comment]
@gabemontero tested and works perfectly. Many thanks for your efforts!

**Comment by gabemontero** [comment]
Great!  Thanks for giving it a go @benemon - glad to help.
