### ISSUE TITLE
Concurrent builds with differing parameters from environment variables are not possible

### ISSUE THREAD

**Issue by elyscape** [openshift/jenkins-plugin#26]
When a build is started with an OpenShift build step, it reads the parameters assigned in the job configuration. Then, it checks to see if any of the values correspond to environment variables. If they do, it uses the values of the environment variables instead of the value in the job config. This is all fine. The problem is that the way it does this is to actually [change the values in the job configuration itself](https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/IOpenShiftPlugin.java#L138-L160), run the build step, and then [change them back](https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/IOpenShiftPlugin.java#L185-L211). As a side effect, attempting to run the same build multiple times concurrently (or, sometimes, just multiple times sequentially with minimal delay between them) with differing values for the environment variables will result in the build step using the first parameters twice.

To illustrate the issue, here is a build step:

![before a build](https://cloud.githubusercontent.com/assets/792695/13612324/c064a872-e51b-11e5-8d39-6e55cf47fd01.png)

And here is that same build step during a build:

![during a build](https://cloud.githubusercontent.com/assets/792695/13612428/54c9bc50-e51c-11e5-8a4d-6d56b1b62841.png)

Any additional builds invoked while the first build is in progress will get those values, rather than the ones passed as parameters.

**Comment by gabemontero** [comment]
Yep, that is how the var substitution for the steps works.  My prior testing though had lead me to believe a new instance of the step was instantiated.  Obviously appears otherwise.

Have an idea on how to reconcile (an alternative approach I had originally considered).  I may be able to start as soon as tomorrow on it.

**Comment by elyscape** [comment]
I don't know exactly how it's done, but a lot of other plugins support parameter expansion. For example, the [CloudBees Docker Build and Publish plugin](https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Build+and+Publish+plugin):

![parameter expansion](https://cloud.githubusercontent.com/assets/792695/13619260/e2275588-e53c-11e5-94a6-ba8e816c1208.png)

**Comment by elyscape** [comment]
Update: looks like it's done by using [the Token Macro plugin](https://wiki.jenkins-ci.org/display/JENKINS/Token+Macro+Plugin).

**Comment by gabemontero** [comment]
Thanks for the pointer, though in looking at the token macro code and the example usage from a couple of plugins, it won't serve as a total plug in play replacement for the current code.  That said, we may want to leverage it (either as part of this fix, or future enhancements).

**Comment by gabemontero** [comment]
@elyscape : I've delievered the fix for this with commit https://github.com/openshift/jenkins-plugin/commit/dfecb8e4da2e002c0603793aff87488d033f363e to this repo.

Also, if you would not rather build the plugin hpi file yourself to try it out, you can obtain a built plugin hpi file with this fix at https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/lastBuild/artifact/plugin/openshift-pipeline.hpi

Otherwise, if you are going to wait for a new OpenShift Jenkins image getting built with a plugin update with this fix, it may be a few weeks before we do that (though something earlier is not necessarily out of the question).

But if you can try it out beforehand, that would be awesome, and of course reopen this issue / open new issues as needed.

thanks

**Comment by elyscape** [comment]
Just tried it out and it looks good to me. Thanks for your help!

**Comment by gabemontero** [comment]
Cool deal!  Thanks for trying it out and confirming!
