### ISSUE TITLE
Create OpenShift Resource(s) task tries to create resource in wrong project

### ISSUE THREAD

**Issue by ullgren** [openshift/jenkins-plugin#45]
Using the "Create OpenShift Resource(s)" task it tries to create the resource in the same project as the Jenkins service run in even when specifying another project in the task configuration. 

![jenkins-create-resource-buildstep-config](https://cloud.githubusercontent.com/assets/536239/16521323/6491f72c-3f96-11e6-9f0c-22478942c68b.png)

[job execution log](https://github.com/openshift/jenkins-plugin/files/343426/jenkins-create-resource-error.txt)

**Comment by gabemontero** [comment]
Yep, we don't currently parse the json/yaml for namespace specifications and adjust the REST call accordingly.  Same goes for the resource deletion steps.

We minimally need to document the behavior, if not change the implementation to handle this.

@bparees - any initial opinions on what we want to do here (I'm leaning toward code change, but with the background around create/delete, I don't think it is a given)

**Comment by bparees** [comment]
not certain i understand the behavior.

if the resource being created does NOT itself define a namespace in the metadata, does it get created in the namespace defined by the build step (and defaults to the current jenkins namespace)?

and if the resource does define a namespace in the metadata, does it get created in that namespace?

**Comment by gabemontero** [comment]
On Fri, Jul 1, 2016 at 11:32 AM, Ben Parees notifications@github.com
wrote:

> not certain i understand the behavior.
> 
> if the resource being created does NOT itself define a namespace in the
> metadata, does it get created in the namespace defined by the build step
> (and defaults to the current jenkins namespace)?
> 
> and if the resource does define a namespace in the metadata, does it get
> created in that namespace?

Right now the create build step always creates all resources in the
namespace specified  in the create build step config (or if none is
specified there, it uses the namespace of the jenkins service mounted into
the pod
for all objects it creates), using the auth token specified (where if if
none is specified, it using the one for the service account mounted into
the pod).

It ignores any specification of resource in the JSON/YAML.   Aside from
doing basic JSON/YAML format verification, we stop parsing the JSON at the
'kind' (we need to know the 'kind'
to know which REST endpoint to hit).

Manipulating resources in other namespaces of course gets into either
giving the jenkins serivce account  edit access to those namespaces, or
providing auth tokens for any namespace
noted in the JSON/YAML.

If we want to go down this path, the timing of any changes is also a
consideration (at some point we'll want to move to a newer version of the
openshift-restclient-java component, where they
have improved the API around generic resource creation, which we might want
to switch to).

**Comment by bparees** [comment]
what does "oc create -f foo.yaml -n somenamespace" do when foo.yaml specifies a namespace?  we should expect to align with that.

**Comment by ullgren** [comment]
Note that in this case I did **NOT** set a namespace in the yaml text field. 

I did however put a namespace/projectname in the text filed that say "The name of the project to create the resource in". I would have thought that this was the equivalent to having "-n demo" on the commandline when calling the oc binary. However this namespace/projectname is ignored.

So it is not (at least not in my case) a problem where the "-n" say one thing and the yaml another.

**Comment by gabemontero** [comment]
FYI - I've reproduced this and am working on a fix.

**Comment by gabemontero** [comment]
So I believe the problem where the namespace specified in the build step field was not used was introduced with commit 373afaa904f1db7af62f967a11f82e81b857216e (from about 4 weeks ago).

This bug actually affects all the build steps, not just the create resources one.  So I'm bumping the priority to p2.

With the fix I will soon commit, if you specify a project that is different from the project jenkins is running in, as well as the associated default service account token for said project, and as well as providing the default service account token edit access for said project, you can create resources.

For honoring the namespace within the json/yaml, I'm going to look into a fix of the following form:
- the token provided to the step has been given edit access to any project listed in the json/yaml (the doc will be updated with this requirement); I don't want to introduce a change where we specify multiple tokens for each project 
- i'll then fetch a rest client to the specific namespace as part of processing each resource

If this change proves straightforward, I'll include it in the fix as well.  Otherwise, I'll just incorporate the fix to honor the namespace, and document the restriction of not honoring the namespace in the json/yaml for now, and track lifting this restriction our trello card that is handling rebasing the plugin on the newer version of the rest client.

**Comment by gabemontero** [comment]
OK, I got the pulling of the namespace from the json/yaml working easily enough.  Will include this change, along with the doc updates mentioned previously around permissions for the service account.

**Comment by gabemontero** [comment]
Delivered fixes with https://github.com/openshift/jenkins-plugin/commit/895c47ba363b3524df70adba40f3b001daf46108

Built, pre-release version of the plugin with this change can be found [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/23/s3/download/openshift-pipeline.hpi)

When it comes out, V1.0.21 will be the official release with the fix.

Closing this out - please reopen if something does not seem right wrt the fix provided.
