### ISSUE TITLE
Build trigger fails waiting for logs

### ISSUE THREAD

**Issue by rhamilto** [openshift/jenkins-plugin#47]
this is the jenkins console output.  @bparees to provide color.

```
OpenShift Build myproject/sample-pipeline-1
[Pipeline] node
Still waiting to schedule task
584400d9638 is offline
Running on 6a00e94b7c7 in /tmp/workspace/sample-pipeline
[Pipeline] {
[Pipeline] stage (build)
Entering stage build
Proceeding
[Pipeline] openshiftBuild


Starting the "Trigger OpenShift Build" step with build config "ruby-sample-build" from the project "myproject".
  Started build "ruby-sample-build-1" and waiting for build completion ...


Exiting "Trigger OpenShift Build" unsuccessfully; build "ruby-sample-build-1" has completed with status:  [null].
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: "Trigger OpenShift Build" failed
Finished: FAILURE
```

**Comment by bparees** [comment]
@gabemontero ptal, this build took a long time to start, possibly because it was pulling the image.  It appears in the meantime something timed out in the plugin and it decided the build was failed (with a null status).  I think it may have timed out waiting for the logs to start, because the build step is configured to stream the logs back.

**Comment by gabemontero** [comment]
Can we re-run this with verbose logging turned on (see the readme for
instructions)?

There are configurable timeout settings (also explained in the readme).  We
could explore changing the default if the new pipeline stuff needs more
elbow room.

**Comment by bparees** [comment]
it's probably going to be hard to recreate since it only happened when the image was being pulled (@rhamilto you could try docker rmi'ing the image locally so it has to be re-pulled next time).

at a minimum it seems like if we hit a timeout we need a better status report.

what is the default timeout?

**Comment by bparees** [comment]
(I don't think the pipeline stuff is causing the timeout to need to be longer, since this was still just a straightforward "trigger a build and wait for it" build step)

**Comment by rhamilto** [comment]
@bparees, i docker rmi-ed the image (and dependent images) and was able to reproduce the build failure on the initial build.  The subsequent second build was successful (as it was earlier).

**Comment by gabemontero** [comment]
@bparees - the default build timeout is 5 minutes.

Pending an update to that amount, I can certainly work on having the error message indicate that we quit waiting on the build to complete.  I'll start on that in a bit.

**Comment by bparees** [comment]
@gabemontero that's just a timeout waiting for the build to start, not a timeout waiting for the build to complete, right?

**Comment by gabemontero** [comment]
@bparees no, it currently is the timeout to complete.

**Comment by bparees** [comment]
@gabemontero I think we should raise that default to at least 15 mins then. (Along w/ making the error clear about why we gave up).

**Comment by gabemontero** [comment]
@bparees will do ... I _may_ have found a scenario where we quit waiting too soon.  Addressing that will be part of the change.

**Comment by gabemontero** [comment]
My proposal on the new message:

`Exiting "Trigger OpenShift Build" unsuccessfully; build "ruby-sample-build-1" :  did not complete successfully within the configured timeout;  last reported status: [NotStarted].`

**Comment by bparees** [comment]
can we print the timeout value in the message?

otherwise lgtm

**Comment by gabemontero** [comment]
Sure i'll add that

**Comment by gabemontero** [comment]
Fixes introduced with https://github.com/openshift/jenkins-plugin/commit/9e4c19fded368e5b931342f156f2e93b5350f8a9

A pre-release version of the plugin with the fix is located [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/24/s3/download/openshift-pipeline.hpi)

V1.0.21 will be the released version with this fix.
